FROM --platform=linux/arm64 ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
ENV PKG_CONFIG_SYSROOT_DIR=/usr/aarch64-linux-gnu
ENV PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
ENV PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig
ENV CC=aarch64-linux-gnu-gcc
ENV CXX=aarch64-linux-gnu-g++
ENV TARGET=aarch64-unknown-linux-gnu

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl git gnupg2 build-essential \
    libwebkit2gtk-4.0-dev \
    libssl-dev libgtk-3-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev libglib2.0-dev \
    libgdk-pixbuf2.0-dev libgtk-3-dev \
    pkg-config \
    cmake \
    python3 \
    nodejs npm \
    aarch64-linux-gnu-gcc \
    aarch64-linux-gnu-g++ \
    qemu-user-static

# Install Rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y && \
    ~/.cargo/bin/rustup target add aarch64-unknown-linux-gnu

# Set paths
ENV PATH="/root/.cargo/bin:$PATH"

# Add project
WORKDIR /build
COPY . .

# Build frontend
RUN npm install && npm run build

# Build tauri
RUN npm run tauri build -- --target aarch64-unknown-linux-gnu
